//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProductSyatemMariam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int IDTrade { get; set; }
        public int IDGoods { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PriceForPic { get; set; }
        public Nullable<System.DateTime> DatePayment { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Register Register { get; set; }
    }
}
