//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProductSyatemMariam
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillForYou
    {
        public string Name { get; set; }
        public int Quantity { get; set; }
        public decimal PriceForPic { get; set; }
        public System.DateTime DatePayment { get; set; }
        public int IDGoods { get; set; }
        public int IDG { get; set; }
        public int IDReg { get; set; }
    }
}
